services:

  api:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    ports:
      - "8000:8000"
    networks:
      - lexicom

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - lexicom
    volumes:
      - redis_data:/data


networks:
  lexicom: { }

volumes:
  redis_data: { }